{
    "name": "build",
    "on": {
        "workflow_dispatch" : {}
    },
    "jobs": {
        "work": {
#            "runs-on": "ubuntu-latest",
            "runs-on": "macos-latest-xlarge",
            "steps": [
                {
                    "uses": "actions/checkout@v4"
                },
                {
                    "name": "work",
                    "run": "bash -xeu ./executed_from_ci.sh"
                }
            ]
        }
    }
}
